# Generated by Django 5.0.7 on 2025-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_passwordresetotp_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
