# Generated by Django 5.0.7 on 2025-10-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
